const SHOWSEARCHPANEL = ' SHOWSEARCHPANEL';
const HIDDENSEARCHPANEL = ' HIDDENSEARCHPANEL';
const SHOWLOGINPANEL = ' SHOWLOGINPANEL';
const HIDDENLOGINPANEL = ' HIDDENLOGINPANEL';
const LOGINUPDATE ='LOGINUPDATE';
const USERNAMEUPDATE ='USERNAMEUPDATE';

export { USERNAMEUPDATE,SHOWSEARCHPANEL, HIDDENSEARCHPANEL, SHOWLOGINPANEL, HIDDENLOGINPANEL, LOGINUPDATE};